"""Init migrations.

Revision ID: 96d72460a55e
Revises:
Create Date: 2023-12-21 12:10:37.893923

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "96d72460a55e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("cpf", sa.String(length=11), nullable=True),
        sa.Column("birth_date", sa.DateTime(), nullable=True),
        sa.Column("username", sa.String(length=300), nullable=True),
        sa.Column("password", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "account",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("balance", sa.Float(), nullable=True),
        sa.Column("daily_withdrawal_limit", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("account_type", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "transaction",
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.execute(
        """
        INSERT INTO user (name, cpf, birth_date, username, password)
        VALUES ('User', '12345678901', '1990-01-01', 'user', 'scrypt:32768:8:1$yH1PbuoUexySmPtH$a5942a8817971d020ef0aee668bf63627751741d0d88f4b35125de80412dfbe7b6df90fb1d577a5d454a0ee0e01bb9ea67fc0b12b10c0181863dc63395eefc73');
        """,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    op.drop_table("account")
    op.drop_table("user")
    # ### end Alembic commands ###
